// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: agent.proto

package opspilotv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Hostname       string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os             string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Distribution   string                 `protobuf:"bytes,3,opt,name=distribution,proto3" json:"distribution,omitempty"`
	Version        string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Architecture   string                 `protobuf:"bytes,5,opt,name=architecture,proto3" json:"architecture,omitempty"`
	Capabilities   []string               `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	BootstrapToken string                 `protobuf:"bytes,7,opt,name=bootstrap_token,json=bootstrapToken,proto3" json:"bootstrap_token,omitempty"`
	IpAddress      string                 `protobuf:"bytes,8,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Environment    string                 `protobuf:"bytes,9,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RegisterRequest) GetDistribution() string {
	if x != nil {
		return x.Distribution
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *RegisterRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterRequest) GetBootstrapToken() string {
	if x != nil {
		return x.BootstrapToken
	}
	return ""
}

func (x *RegisterRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RegisterRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

type RegisterResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AgentId              string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Approved             bool                   `protobuf:"varint,2,opt,name=approved,proto3" json:"approved,omitempty"`
	Message              string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	HeartbeatIntervalSec int32                  `protobuf:"varint,4,opt,name=heartbeat_interval_sec,json=heartbeatIntervalSec,proto3" json:"heartbeat_interval_sec,omitempty"`
	ClientCertPem        string                 `protobuf:"bytes,5,opt,name=client_cert_pem,json=clientCertPem,proto3" json:"client_cert_pem,omitempty"`
	ClientKeyPem         string                 `protobuf:"bytes,6,opt,name=client_key_pem,json=clientKeyPem,proto3" json:"client_key_pem,omitempty"`
	CaCertPem            string                 `protobuf:"bytes,7,opt,name=ca_cert_pem,json=caCertPem,proto3" json:"ca_cert_pem,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetHeartbeatIntervalSec() int32 {
	if x != nil {
		return x.HeartbeatIntervalSec
	}
	return 0
}

func (x *RegisterResponse) GetClientCertPem() string {
	if x != nil {
		return x.ClientCertPem
	}
	return ""
}

func (x *RegisterResponse) GetClientKeyPem() string {
	if x != nil {
		return x.ClientKeyPem
	}
	return ""
}

func (x *RegisterResponse) GetCaCertPem() string {
	if x != nil {
		return x.CaCertPem
	}
	return ""
}

type HeartbeatRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AgentId          string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CpuUsagePercent  float64                `protobuf:"fixed64,2,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	MemoryUsageBytes int64                  `protobuf:"varint,3,opt,name=memory_usage_bytes,json=memoryUsageBytes,proto3" json:"memory_usage_bytes,omitempty"`
	MemoryTotalBytes int64                  `protobuf:"varint,4,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	DiskUsagePercent float64                `protobuf:"fixed64,5,opt,name=disk_usage_percent,json=diskUsagePercent,proto3" json:"disk_usage_percent,omitempty"`
	LoadAvg_1M       float64                `protobuf:"fixed64,6,opt,name=load_avg_1m,json=loadAvg1m,proto3" json:"load_avg_1m,omitempty"`
	ActiveTasks      int32                  `protobuf:"varint,7,opt,name=active_tasks,json=activeTasks,proto3" json:"active_tasks,omitempty"`
	TimestampUnix    int64                  `protobuf:"varint,8,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *HeartbeatRequest) GetMemoryUsageBytes() int64 {
	if x != nil {
		return x.MemoryUsageBytes
	}
	return 0
}

func (x *HeartbeatRequest) GetMemoryTotalBytes() int64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *HeartbeatRequest) GetDiskUsagePercent() float64 {
	if x != nil {
		return x.DiskUsagePercent
	}
	return 0
}

func (x *HeartbeatRequest) GetLoadAvg_1M() float64 {
	if x != nil {
		return x.LoadAvg_1M
	}
	return 0
}

func (x *HeartbeatRequest) GetActiveTasks() int32 {
	if x != nil {
		return x.ActiveTasks
	}
	return 0
}

func (x *HeartbeatRequest) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

type HeartbeatResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged    bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	HasPendingTasks bool                   `protobuf:"varint,2,opt,name=has_pending_tasks,json=hasPendingTasks,proto3" json:"has_pending_tasks,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetHasPendingTasks() bool {
	if x != nil {
		return x.HasPendingTasks
	}
	return false
}

type ControlStreamMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MessageId string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControlStreamMessage_ExecuteStep
	//	*ControlStreamMessage_CancelStep
	//	*ControlStreamMessage_Ping
	Payload       isControlStreamMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlStreamMessage) Reset() {
	*x = ControlStreamMessage{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlStreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlStreamMessage) ProtoMessage() {}

func (x *ControlStreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlStreamMessage.ProtoReflect.Descriptor instead.
func (*ControlStreamMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ControlStreamMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ControlStreamMessage) GetPayload() isControlStreamMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControlStreamMessage) GetExecuteStep() *ExecuteStepCommand {
	if x != nil {
		if x, ok := x.Payload.(*ControlStreamMessage_ExecuteStep); ok {
			return x.ExecuteStep
		}
	}
	return nil
}

func (x *ControlStreamMessage) GetCancelStep() *CancelStepCommand {
	if x != nil {
		if x, ok := x.Payload.(*ControlStreamMessage_CancelStep); ok {
			return x.CancelStep
		}
	}
	return nil
}

func (x *ControlStreamMessage) GetPing() *PingCommand {
	if x != nil {
		if x, ok := x.Payload.(*ControlStreamMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isControlStreamMessage_Payload interface {
	isControlStreamMessage_Payload()
}

type ControlStreamMessage_ExecuteStep struct {
	ExecuteStep *ExecuteStepCommand `protobuf:"bytes,2,opt,name=execute_step,json=executeStep,proto3,oneof"`
}

type ControlStreamMessage_CancelStep struct {
	CancelStep *CancelStepCommand `protobuf:"bytes,3,opt,name=cancel_step,json=cancelStep,proto3,oneof"`
}

type ControlStreamMessage_Ping struct {
	Ping *PingCommand `protobuf:"bytes,4,opt,name=ping,proto3,oneof"`
}

func (*ControlStreamMessage_ExecuteStep) isControlStreamMessage_Payload() {}

func (*ControlStreamMessage_CancelStep) isControlStreamMessage_Payload() {}

func (*ControlStreamMessage_Ping) isControlStreamMessage_Payload() {}

type ExecuteStepCommand struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	TaskId                   string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	StepId                   string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Action                   string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	ArgumentsJson            string                 `protobuf:"bytes,4,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	TimeoutSeconds           int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	RiskLevel                string                 `protobuf:"bytes,6,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`
	VerificationStrategyJson string                 `protobuf:"bytes,7,opt,name=verification_strategy_json,json=verificationStrategyJson,proto3" json:"verification_strategy_json,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ExecuteStepCommand) Reset() {
	*x = ExecuteStepCommand{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteStepCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteStepCommand) ProtoMessage() {}

func (x *ExecuteStepCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteStepCommand.ProtoReflect.Descriptor instead.
func (*ExecuteStepCommand) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteStepCommand) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExecuteStepCommand) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *ExecuteStepCommand) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ExecuteStepCommand) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

func (x *ExecuteStepCommand) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ExecuteStepCommand) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *ExecuteStepCommand) GetVerificationStrategyJson() string {
	if x != nil {
		return x.VerificationStrategyJson
	}
	return ""
}

type CancelStepCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	StepId        string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelStepCommand) Reset() {
	*x = CancelStepCommand{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelStepCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelStepCommand) ProtoMessage() {}

func (x *CancelStepCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelStepCommand.ProtoReflect.Descriptor instead.
func (*CancelStepCommand) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *CancelStepCommand) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CancelStepCommand) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *CancelStepCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type PingCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampUnix int64                  `protobuf:"varint,1,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingCommand) Reset() {
	*x = PingCommand{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingCommand) ProtoMessage() {}

func (x *PingCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingCommand.ProtoReflect.Descriptor instead.
func (*PingCommand) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *PingCommand) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

type AgentStreamMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MessageId string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	AgentId   string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentStreamMessage_Handshake
	//	*AgentStreamMessage_OutputChunk
	//	*AgentStreamMessage_StepResult
	//	*AgentStreamMessage_Pong
	Payload       isAgentStreamMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStreamMessage) Reset() {
	*x = AgentStreamMessage{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStreamMessage) ProtoMessage() {}

func (x *AgentStreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStreamMessage.ProtoReflect.Descriptor instead.
func (*AgentStreamMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *AgentStreamMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *AgentStreamMessage) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentStreamMessage) GetPayload() isAgentStreamMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentStreamMessage) GetHandshake() *HandshakeMessage {
	if x != nil {
		if x, ok := x.Payload.(*AgentStreamMessage_Handshake); ok {
			return x.Handshake
		}
	}
	return nil
}

func (x *AgentStreamMessage) GetOutputChunk() *StepOutputChunk {
	if x != nil {
		if x, ok := x.Payload.(*AgentStreamMessage_OutputChunk); ok {
			return x.OutputChunk
		}
	}
	return nil
}

func (x *AgentStreamMessage) GetStepResult() *StepResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentStreamMessage_StepResult); ok {
			return x.StepResult
		}
	}
	return nil
}

func (x *AgentStreamMessage) GetPong() *PongMessage {
	if x != nil {
		if x, ok := x.Payload.(*AgentStreamMessage_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

type isAgentStreamMessage_Payload interface {
	isAgentStreamMessage_Payload()
}

type AgentStreamMessage_Handshake struct {
	Handshake *HandshakeMessage `protobuf:"bytes,3,opt,name=handshake,proto3,oneof"`
}

type AgentStreamMessage_OutputChunk struct {
	OutputChunk *StepOutputChunk `protobuf:"bytes,4,opt,name=output_chunk,json=outputChunk,proto3,oneof"`
}

type AgentStreamMessage_StepResult struct {
	StepResult *StepResult `protobuf:"bytes,5,opt,name=step_result,json=stepResult,proto3,oneof"`
}

type AgentStreamMessage_Pong struct {
	Pong *PongMessage `protobuf:"bytes,6,opt,name=pong,proto3,oneof"`
}

func (*AgentStreamMessage_Handshake) isAgentStreamMessage_Payload() {}

func (*AgentStreamMessage_OutputChunk) isAgentStreamMessage_Payload() {}

func (*AgentStreamMessage_StepResult) isAgentStreamMessage_Payload() {}

func (*AgentStreamMessage_Pong) isAgentStreamMessage_Payload() {}

type HandshakeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeMessage) Reset() {
	*x = HandshakeMessage{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeMessage) ProtoMessage() {}

func (x *HandshakeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeMessage.ProtoReflect.Descriptor instead.
func (*HandshakeMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *HandshakeMessage) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HandshakeMessage) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HandshakeMessage) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type StepOutputChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	StepId        string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	StreamType    string                 `protobuf:"bytes,3,opt,name=stream_type,json=streamType,proto3" json:"stream_type,omitempty"` // "stdout" or "stderr"
	Data          string                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,5,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepOutputChunk) Reset() {
	*x = StepOutputChunk{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepOutputChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepOutputChunk) ProtoMessage() {}

func (x *StepOutputChunk) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepOutputChunk.ProtoReflect.Descriptor instead.
func (*StepOutputChunk) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *StepOutputChunk) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StepOutputChunk) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *StepOutputChunk) GetStreamType() string {
	if x != nil {
		return x.StreamType
	}
	return ""
}

func (x *StepOutputChunk) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *StepOutputChunk) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

type StepResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TaskId           string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	StepId           string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Action           string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	ExitCode         int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout           string                 `protobuf:"bytes,5,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr           string                 `protobuf:"bytes,6,opt,name=stderr,proto3" json:"stderr,omitempty"`
	DurationMs       int64                  `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Success          bool                   `protobuf:"varint,8,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	VerificationJson string                 `protobuf:"bytes,10,opt,name=verification_json,json=verificationJson,proto3" json:"verification_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StepResult) Reset() {
	*x = StepResult{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepResult) ProtoMessage() {}

func (x *StepResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepResult.ProtoReflect.Descriptor instead.
func (*StepResult) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *StepResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StepResult) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *StepResult) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *StepResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *StepResult) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *StepResult) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *StepResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *StepResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StepResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *StepResult) GetVerificationJson() string {
	if x != nil {
		return x.VerificationJson
	}
	return ""
}

type PongMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampUnix int64                  `protobuf:"varint,1,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PongMessage) Reset() {
	*x = PongMessage{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongMessage) ProtoMessage() {}

func (x *PongMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongMessage.ProtoReflect.Descriptor instead.
func (*PongMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *PongMessage) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\vopspilot.v1\"\xad\x02\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\"\n" +
	"\fdistribution\x18\x03 \x01(\tR\fdistribution\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\"\n" +
	"\farchitecture\x18\x05 \x01(\tR\farchitecture\x12\"\n" +
	"\fcapabilities\x18\x06 \x03(\tR\fcapabilities\x12'\n" +
	"\x0fbootstrap_token\x18\a \x01(\tR\x0ebootstrapToken\x12\x1d\n" +
	"\n" +
	"ip_address\x18\b \x01(\tR\tipAddress\x12 \n" +
	"\venvironment\x18\t \x01(\tR\venvironment\"\x87\x02\n" +
	"\x10RegisterResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bapproved\x18\x02 \x01(\bR\bapproved\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x124\n" +
	"\x16heartbeat_interval_sec\x18\x04 \x01(\x05R\x14heartbeatIntervalSec\x12&\n" +
	"\x0fclient_cert_pem\x18\x05 \x01(\tR\rclientCertPem\x12$\n" +
	"\x0eclient_key_pem\x18\x06 \x01(\tR\fclientKeyPem\x12\x1e\n" +
	"\vca_cert_pem\x18\a \x01(\tR\tcaCertPem\"\xcd\x02\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12*\n" +
	"\x11cpu_usage_percent\x18\x02 \x01(\x01R\x0fcpuUsagePercent\x12,\n" +
	"\x12memory_usage_bytes\x18\x03 \x01(\x03R\x10memoryUsageBytes\x12,\n" +
	"\x12memory_total_bytes\x18\x04 \x01(\x03R\x10memoryTotalBytes\x12,\n" +
	"\x12disk_usage_percent\x18\x05 \x01(\x01R\x10diskUsagePercent\x12\x1e\n" +
	"\vload_avg_1m\x18\x06 \x01(\x01R\tloadAvg1m\x12!\n" +
	"\factive_tasks\x18\a \x01(\x05R\vactiveTasks\x12%\n" +
	"\x0etimestamp_unix\x18\b \x01(\x03R\rtimestampUnix\"c\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12*\n" +
	"\x11has_pending_tasks\x18\x02 \x01(\bR\x0fhasPendingTasks\"\xf9\x01\n" +
	"\x14ControlStreamMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12D\n" +
	"\fexecute_step\x18\x02 \x01(\v2\x1f.opspilot.v1.ExecuteStepCommandH\x00R\vexecuteStep\x12A\n" +
	"\vcancel_step\x18\x03 \x01(\v2\x1e.opspilot.v1.CancelStepCommandH\x00R\n" +
	"cancelStep\x12.\n" +
	"\x04ping\x18\x04 \x01(\v2\x18.opspilot.v1.PingCommandH\x00R\x04pingB\t\n" +
	"\apayload\"\x8b\x02\n" +
	"\x12ExecuteStepCommand\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12%\n" +
	"\x0earguments_json\x18\x04 \x01(\tR\rargumentsJson\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x12\x1d\n" +
	"\n" +
	"risk_level\x18\x06 \x01(\tR\triskLevel\x12<\n" +
	"\x1averification_strategy_json\x18\a \x01(\tR\x18verificationStrategyJson\"]\n" +
	"\x11CancelStepCommand\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"4\n" +
	"\vPingCommand\x12%\n" +
	"\x0etimestamp_unix\x18\x01 \x01(\x03R\rtimestampUnix\"\xc7\x02\n" +
	"\x12AgentStreamMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12=\n" +
	"\thandshake\x18\x03 \x01(\v2\x1d.opspilot.v1.HandshakeMessageH\x00R\thandshake\x12A\n" +
	"\foutput_chunk\x18\x04 \x01(\v2\x1c.opspilot.v1.StepOutputChunkH\x00R\voutputChunk\x12:\n" +
	"\vstep_result\x18\x05 \x01(\v2\x17.opspilot.v1.StepResultH\x00R\n" +
	"stepResult\x12.\n" +
	"\x04pong\x18\x06 \x01(\v2\x18.opspilot.v1.PongMessageH\x00R\x04pongB\t\n" +
	"\apayload\"c\n" +
	"\x10HandshakeMessage\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\x9f\x01\n" +
	"\x0fStepOutputChunk\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12\x1f\n" +
	"\vstream_type\x18\x03 \x01(\tR\n" +
	"streamType\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data\x12%\n" +
	"\x0etimestamp_unix\x18\x05 \x01(\x03R\rtimestampUnix\"\xb0\x02\n" +
	"\n" +
	"StepResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x05 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x06 \x01(\tR\x06stderr\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x03R\n" +
	"durationMs\x12\x18\n" +
	"\asuccess\x18\b \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\t \x01(\tR\ferrorMessage\x12+\n" +
	"\x11verification_json\x18\n" +
	" \x01(\tR\x10verificationJson\"4\n" +
	"\vPongMessage\x12%\n" +
	"\x0etimestamp_unix\x18\x01 \x01(\x03R\rtimestampUnix2\x80\x02\n" +
	"\fAgentService\x12G\n" +
	"\bRegister\x12\x1c.opspilot.v1.RegisterRequest\x1a\x1d.opspilot.v1.RegisterResponse\x12N\n" +
	"\rSendHeartbeat\x12\x1d.opspilot.v1.HeartbeatRequest\x1a\x1e.opspilot.v1.HeartbeatResponse\x12W\n" +
	"\rConnectStream\x12\x1f.opspilot.v1.AgentStreamMessage\x1a!.opspilot.v1.ControlStreamMessage(\x010\x01B\x1eZ\x1copspilot/proto/v1;opspilotv1b\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_agent_proto_goTypes = []any{
	(*RegisterRequest)(nil),      // 0: opspilot.v1.RegisterRequest
	(*RegisterResponse)(nil),     // 1: opspilot.v1.RegisterResponse
	(*HeartbeatRequest)(nil),     // 2: opspilot.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),    // 3: opspilot.v1.HeartbeatResponse
	(*ControlStreamMessage)(nil), // 4: opspilot.v1.ControlStreamMessage
	(*ExecuteStepCommand)(nil),   // 5: opspilot.v1.ExecuteStepCommand
	(*CancelStepCommand)(nil),    // 6: opspilot.v1.CancelStepCommand
	(*PingCommand)(nil),          // 7: opspilot.v1.PingCommand
	(*AgentStreamMessage)(nil),   // 8: opspilot.v1.AgentStreamMessage
	(*HandshakeMessage)(nil),     // 9: opspilot.v1.HandshakeMessage
	(*StepOutputChunk)(nil),      // 10: opspilot.v1.StepOutputChunk
	(*StepResult)(nil),           // 11: opspilot.v1.StepResult
	(*PongMessage)(nil),          // 12: opspilot.v1.PongMessage
}
var file_agent_proto_depIdxs = []int32{
	5,  // 0: opspilot.v1.ControlStreamMessage.execute_step:type_name -> opspilot.v1.ExecuteStepCommand
	6,  // 1: opspilot.v1.ControlStreamMessage.cancel_step:type_name -> opspilot.v1.CancelStepCommand
	7,  // 2: opspilot.v1.ControlStreamMessage.ping:type_name -> opspilot.v1.PingCommand
	9,  // 3: opspilot.v1.AgentStreamMessage.handshake:type_name -> opspilot.v1.HandshakeMessage
	10, // 4: opspilot.v1.AgentStreamMessage.output_chunk:type_name -> opspilot.v1.StepOutputChunk
	11, // 5: opspilot.v1.AgentStreamMessage.step_result:type_name -> opspilot.v1.StepResult
	12, // 6: opspilot.v1.AgentStreamMessage.pong:type_name -> opspilot.v1.PongMessage
	0,  // 7: opspilot.v1.AgentService.Register:input_type -> opspilot.v1.RegisterRequest
	2,  // 8: opspilot.v1.AgentService.SendHeartbeat:input_type -> opspilot.v1.HeartbeatRequest
	8,  // 9: opspilot.v1.AgentService.ConnectStream:input_type -> opspilot.v1.AgentStreamMessage
	1,  // 10: opspilot.v1.AgentService.Register:output_type -> opspilot.v1.RegisterResponse
	3,  // 11: opspilot.v1.AgentService.SendHeartbeat:output_type -> opspilot.v1.HeartbeatResponse
	4,  // 12: opspilot.v1.AgentService.ConnectStream:output_type -> opspilot.v1.ControlStreamMessage
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[4].OneofWrappers = []any{
		(*ControlStreamMessage_ExecuteStep)(nil),
		(*ControlStreamMessage_CancelStep)(nil),
		(*ControlStreamMessage_Ping)(nil),
	}
	file_agent_proto_msgTypes[8].OneofWrappers = []any{
		(*AgentStreamMessage_Handshake)(nil),
		(*AgentStreamMessage_OutputChunk)(nil),
		(*AgentStreamMessage_StepResult)(nil),
		(*AgentStreamMessage_Pong)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
